const STAFF_TOP = 60;
const LINE_SPACING = 12;
const NOTE_WIDTH = 30;
const STAFF_PADDING = 40;
const BEATS_PER_MEASURE = 4;

export { STAFF_TOP, LINE_SPACING, NOTE_WIDTH, STAFF_PADDING, BEATS_PER_MEASURE };
